version: "3"
services:
  database:
    image: postgres:alpine
    restart: always
    hostname: database

    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "games", "-U", "postgres" ]
      timeout: 5s
      interval: 10s
      retries: 10

    ports:
      #- "5433:5432"
      - "5432:5432"

    networks:
      - sashnevskiy

    environment: 
      - "POSTGRES_PASSWORD=mysecretpassword"
      - "POSTGRES_DB=games"
      - "POSTGRES_USER=postgres"

    volumes:
      - "./match_prediction/init-sql:/docker-entrypoint-initdb.d"

  web:
    restart: always
    build: .

    hostname: "web"
    env_file: .env
    networks:
      - sashnevskiy
      
    ports:
      - "5005:5005"

    depends_on:
      database:
        condition: service_healthy

networks:
  sashnevskiy:
    name: sashnevskiy
    driver: bridge