version: "3"
services:
  database:
    image: postgres:latest
    #restart: always
    hostname: "database"

    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "games", "-U", "postgres" ]
      timeout: 45s
      interval: 10s
      retries: 10

    ports:
      - "5432:5432"

    networks:
      - sashnevskiy

    environment:
      - "POSTGRES_PASSWORD=mysecretpassword"
      - "POSTGRES_DB=games"

    volumes:
      - "/home/ubuntu/ubuntu/match-prediction/init-sql:/docker-entrypoint-initdb.d/"

  web:
    platform: linux/amd64
    #restart: always
    build: .

    hostname: "web"
    networks:
      - sashnevskiy

    environment:
      - "FLASK_RUN_HOST=0.0.0.0"
      - "FLASK_ENV=development"

    ports:
      - "5000:5000"

    # Link database container to app container 
    # for reachability.

    depends_on:
      database:
        condition: service_healthy

networks:
  sashnevskiy:
    name: sashnevskiy
    driver: bridge